# ===========================
# SERVER
# ===========================
server.port=8080
spring.output.ansi.enabled=always

# ===========================
# DATABASE
# ===========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fintech_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Admin@123}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================
# JPA / HIBERNATE
# ===========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# ===========================
# FLYWAY
# ===========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


# ===========================
# APPLICATION
# ===========================
spring.application.name=fintech-platform

# ===========================
# SECURITY
# ===========================
jwt.secret=${JWT_SECRET:fintech-super-secret-jwt-key-change-this-in-production}
jwt.expiration=${JWT_EXPIRATION:86400000}

# ===========================
# INVESTMENT RATES
# ===========================
investment.fd.interest-rate.default=7.00
investment.fd.penalty.premature-withdrawal=1.00
investment.rd.interest-rate.default=6.50