# ===========================
# SERVER
# ===========================
server.port=8080

# ===========================
# DATABASE
# ===========================
spring.datasource.url=jdbc:postgresql://localhost:5432/fintech_db
spring.datasource.username=postgres
spring.datasource.password=Admin@123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================
# JPA / HIBERNATE
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===========================
# APPLICATION
# ===========================
spring.application.name=fintech-platform

# ===========================
# SECURITY (temporary - will move to env variables)
# ===========================
jwt.secret=fintech-super-secret-jwt-key-change-this-in-production
jwt.expiration=86400000